{
  imports = [
    ../modules/packages.nix
    ./blocks.nix
    ./cfg.nix
    ./commit.nix
    ./cop.nix
    ./darwin-switch.nix
    ./fuck.nix
    ./lsh.nix
    ./mi.nix
    ./nish.nix
    ./nix-clean.nix
    ./nix-get-sha256.nix
    ./nix-switch.nix
    ./rm-result.nix
    ./sec.nix
    ./vault.nix
    ./wipe-linux.nix
  ];
}
